AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bundle/**/*'
    - 'vendor/bundle/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 15
Style/Documentation:
  Enabled: false

# The following are disabled by default, but we want them enabled
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Rails/SaveBang:
  Enabled: true
Style/AutoResourceCleanup:
  Enabled: true
Style/CollectionMethods:
  Enabled: true
Style/ImplicitRuntimeError:
  Enabled: true
Style/MethodCalledOnDoEndBlock:
  Enabled: true
Style/OptionHash:
  Enabled: true
Style/ReturnNil:
  Enabled: true
Style/Send:
  Enabled: true
Style/SingleLineBlockParams:
  Enabled: true
Style/StringMethods:
  Enabled: true

# # Changing the default config
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
